#!/usr/bin/env bash
set -euo pipefail

# Creates:
#   /tmp/aptos-dstest/nodes/v0/node.yaml, data/, genesis/
#   ...

# ------------------------------------------
# Resolve paths and environment variables
# ------------------------------------------

# Expect Makefile to pass these (or rely on defaults):
#   APTOS_CORE           : path to aptos-core
#   BASE_DIR             : where genesis and node configurations live
#   GENESIS_DIR          : path to the genesis directory
#   NUM_NODES            : number of replicas in the local network
#   BASE_PORT            : the base port for node network configurations
#   PYTHON_BIN           : python with pyyaml installed (e.g., venv)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APTOS_CORE="${APTOS_CORE:-${SCRIPT_DIR}/../../aptos-core}"

BASE_DIR="${BASE_DIR:-/tmp/aptos-dstest}"
GENESIS_DIR="${GENESIS_DIR:-${BASE_DIR}/genesis}"
NODES_DIR="${BASE_DIR}/nodes"

NUM_NODES="${NUM_NODES:-4}"
BASE_PORT="${BASE_PORT:-8000}"

# ------------------------------------------
# [0/1]: Sanity checks
# ------------------------------------------

TEMPLATE="${APTOS_CORE}/docker/compose/aptos-node/validator.yaml"
if [[ ! -f "${TEMPLATE}" ]]; then
  echo "ERROR: Could not find validator template at: ${TEMPLATE}"
  echo "Search for it with: find \"${APTOS_CORE}\" -path '*aptos-node*' -name 'validator.yaml' | head"
  exit 1
fi

test -f "${GENESIS_DIR}/genesis.blob" || { 
    echo "Missing ${GENESIS_DIR}/genesis.blob"; 
    exit 1; 
}

test -f "${GENESIS_DIR}/waypoint.txt"  || { 
    echo "Missing ${GENESIS_DIR}/waypoint.txt"; 
    exit 1; 
}

"${PYTHON_BIN}" -c 'import yaml' >/dev/null 2>&1 || {
  echo "ERROR: PYTHON_BIN cannot import PyYAML (import yaml failed)."
  echo "Run: make setup and ensure PYTHON_BIN points to the venv python."
  exit 1
}

# ----------------------------------------------------------
# [1/1]: Assemble configurations for each node (node.yaml)
# ----------------------------------------------------------

# Port plan per node i:
# - REST API:          BASE_PORT + i*10 + 0
# - WARP PORT:         BASE_PORT + i*10 + 6
# - ADMIN PORT:        BASE_PORT + i*10 + 7
# - BACKUP PORT:       BASE_PORT + i*10 + 8
# - VAL_LISTEN_PORT    BASE_PORT + i + 1

mkdir -p "${NODES_DIR}"

for i in $(seq 0 $((NUM_NODES - 1))); do
  NODE_DIR="${NODES_DIR}/v${i}"
  mkdir -p "${NODE_DIR}/data" "${NODE_DIR}/genesis"

  cp -f "${GENESIS_DIR}/genesis.blob" "${NODE_DIR}/genesis/genesis.blob"
  cp -f "${GENESIS_DIR}/waypoint.txt"  "${NODE_DIR}/genesis/waypoint.txt"

  # Identity blobs: generated by `aptos genesis generate-keys`
  KEY_DIR="${GENESIS_DIR}/n${i}_keys"

  test -f "${KEY_DIR}/validator-identity.yaml" || {
    echo "ERROR: Missing ${KEY_DIR}/validator-identity.yaml"
    echo "Check: ls -la ${KEY_DIR}"
    exit 1
  }
  
  cp -f "${KEY_DIR}/validator-identity.yaml" "${NODE_DIR}/genesis/validator-identity.yaml"

  # Some templates reference validator-full-node-identity.yaml; copy if present
  if [[ -f "${KEY_DIR}/validator-full-node-identity.yaml" ]]; then
    cp -f "${KEY_DIR}/validator-full-node-identity.yaml" "${NODE_DIR}/genesis/validator-full-node-identity.yaml"
  fi

  API_PORT=$((BASE_PORT + i*10 + 0))
  WARP_PORT=$((BASE_PORT + i*10 + 6))      # inspection_service (warp) replaces default 6186
  ADMIN_PORT=$((BASE_PORT + i*10 + 7))     # admin_service replaces default port(s)
  BACKUP_PORT=$((BASE_PORT + i*10 + 8))
  VAL_LISTEN_PORT=$((BASE_PORT + i + 1))

  # Start from template and patch paths/ports.
  "${PYTHON_BIN}" - <<PY
import yaml, pathlib

tmpl = pathlib.Path("${TEMPLATE}")
outp = pathlib.Path("${NODE_DIR}/node.yaml")

cfg = yaml.safe_load(tmpl.read_text()) or {}

node_dir = pathlib.Path("${NODE_DIR}")

# --- Paths
cfg.setdefault("base", {})
cfg["base"]["data_dir"] = str(node_dir / "data")

cfg.setdefault("execution", {})
cfg["execution"]["genesis_file_location"] = str(node_dir / "genesis" / "genesis.blob")

cfg["base"].setdefault("waypoint", {})
cfg["base"]["waypoint"]["from_file"] = str(node_dir / "genesis" / "waypoint.txt")

identity_path = str(node_dir / "genesis" / "validator-identity.yaml")

# validator_network.identity.path
vn = cfg.get("validator_network")
if isinstance(vn, dict):
    ident = vn.get("identity")
    if isinstance(ident, dict):
        ident["path"] = identity_path

# consensus.safety_rules...identity_blob_path
cons = cfg.get("consensus")
if isinstance(cons, dict):
    sr = cons.get("safety_rules")
    if isinstance(sr, dict):
        init = sr.get("initial_safety_rules_config")
        if isinstance(init, dict):
            ff = init.get("from_file")
            if isinstance(ff, dict):
                ff["identity_blob_path"] = identity_path
                wp = ff.get("waypoint")
                if isinstance(wp, dict):
                    wp["from_file"] = str(node_dir / "genesis" / "waypoint.txt")

# --- Ports
api = cfg.get("api")
if isinstance(api, dict):
    api["enabled"] = False
    api["address"] = f"0.0.0.0:{${API_PORT}}"

# internal services to avoid collisions
cfg["inspection_service"] = cfg.get("inspection_service") or {}
if isinstance(cfg["inspection_service"], dict):
    cfg["inspection_service"].pop("address", None)
    cfg["inspection_service"]["port"] = int(${WARP_PORT})

cfg["admin_service"] = cfg.get("admin_service") or {}
if isinstance(cfg["admin_service"], dict):
    cfg["admin_service"].pop("address", None)
    cfg["admin_service"]["port"] = int(${ADMIN_PORT})

cfg.setdefault("storage", {})
cfg["storage"]["backup_service_address"] = f"127.0.0.1:{${BACKUP_PORT}}"

# Disable VFN/fullnode networks to avoid port collisions and keep dsTest focused on validator network
cfg["full_node_networks"] = []

# --- Validator network
vn = cfg.get("validator_network") or {}
cfg["validator_network"] = vn

# Turn off on-chain discovery; dsTest + patched seeds will handle peering
vn["discovery_method"] = "none"

# Bind validator network to dsTest replica listen port (BASE_PORT + i + 1)
vn["listen_address"] = f"/ip4/0.0.0.0/tcp/{${VAL_LISTEN_PORT}}"

# Ensure these exist (seed patcher will overwrite seeds)
vn.setdefault("seed_addrs", {})
vn.setdefault("seeds", {})

outp.write_text(yaml.safe_dump(cfg, sort_keys=False))
print("Wrote", outp)
PY

done

echo "Generated node configs under: ${NODES_DIR}"
echo "Try: ls -la ${NODES_DIR}/v0 && sed -n '1,120p' ${NODES_DIR}/v0/node.yaml"