strategies:
  #- byzzfuzz
  - evo_aptos

benchmarks:
  #- aptos
  - bug1
  #- bug2
  #- bug3

fitness:
  - time_fitness
  #- round_stress_fitness
  #- block_height_skew_fitness
  #- round_timeout_count_fitness
  #- vote_fragmentation_fitness
  #- quorum_store_fitness

max_parallel_workers: 2
run_slots: 2
run_tag_prefix: "-evo"
run_offset: 0
run_offset_stride: 1000

population_size: 4   # population of (λ) individuals
mu: 2                # Parent count (μ) for (μ+λ) selection in DEAP
total_num_tests: 100 # for evo, it's 100/4=25 generations with 4 individuals each

max_partition_duration: 2000
seed: 42

dstest:
  num_nodes: 6
  num_client_accounts: 2
  # Byzzfuzz initial params; during mutations these can change
  c: 2
  d: 1
  r: 6
  iterations: 1
  block_height_max: 10
  steps: 3000 #2300
  recovery_seconds: 30
  liveness_timeout: 60