TestConfig:
  Name: aptos-b2-c2d1
  Experiments: 1
  Iterations: 100
  WaitDuration: 50
  StartupDuration: 10

SchedulerConfig:
  Type: "byzzfuzz"
  Steps: 1500
  Seed: 42
  ClientRequests: 0
  Params: {"c": 2, "d": 1, "r": 6, "recovery_seconds": 30}

NetworkConfig:
  BaseReplicaPort: 9000
  BaseInterceptorPort: 11000
  Protocol: "aptostcp"
  MessageType: Aptos

FaultConfig:
  Faults: []

ProcessConfig:
  NumReplicas: 6
  Timeout: 150
  OutputDir:  output/aptos-b2-c2d1/20260609_183913
  ReplicaScript: aptos/aptos_server.sh
  # NOTE: each ClientScripts entry must have a different clientId
  # NOTE: the scripts are executed in the given order.
  ClientScripts:
    - aptos/aptos_client.sh 0 0 3 2
    - aptos/aptos_client.sh 1 3 3 3
  CleanScript: aptos/aptos_clean.sh
  ReplicaParams:
    - "0 /tmp/aptos-dstest-c2d1"
    - "1 /tmp/aptos-dstest-c2d1"
    - "2 /tmp/aptos-dstest-c2d1"
    - "3 /tmp/aptos-dstest-c2d1"
    - "4 /tmp/aptos-dstest-c2d1"
    - "5 /tmp/aptos-dstest-c2d1"
