TestConfig:
  Name: aptos-localnet
  Experiments: 1
  Iterations: 10
  WaitDuration: 50
  StartupDuration: 10

SchedulerConfig:
  Type: "byzzfuzz"
  Steps: 2500
  Seed: 42
  ClientRequests: 0
  Params: {"c": 1, "d": 1, "r": 6, "recovery_seconds": 30}

NetworkConfig:
  BaseReplicaPort: 8000
  BaseInterceptorPort: 10000
  Protocol: "aptostcp"
  MessageType: Aptos

FaultConfig:
  Faults: []

ProcessConfig:
  NumReplicas: 4
  Timeout: 150
  OutputDir:  output/aptos/20260602_152540
  ReplicaScript: aptos/aptos_server.sh
  # NOTE: each ClientScripts entry must have a different clientId
  # NOTE: the scripts are executed in the given order.
  ClientScripts:
    - aptos/aptos_client.sh 0 0 5 4
    - aptos/aptos_client.sh 1 3 2 5
    - aptos/aptos_client.sh 2 1 5 6
    - aptos/aptos_client.sh 3 2 3 7
  CleanScript: aptos/aptos_clean.sh
  ReplicaParams:
    - "0 /tmp/aptos-dstest"
    - "1 /tmp/aptos-dstest"
    - "2 /tmp/aptos-dstest"
    - "3 /tmp/aptos-dstest"
